name: Sync Fork with Original Repository
on:
  schedule:
    - cron: '0 12 * * *' # Run every day at 12:00 PM UTC
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout original repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/CVEProject/cvelistV5.git
          ref: main
          token: ${{ secrets.CVE5_SECRET }}

      - name: Checkout forked repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/filipdadgar/cvelistV5
          ref: main

      - name: Merge changes from original repository
        run: git merge --no-edit --no-ff origin/main

      - name: Push changes to forked repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CVE5_SECRET }}
